on: [push]

name: AzureLoginSample


jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
            az account show
    - name: Azure PowerShell Action
      uses: Azure/powershell@v1
      with:
          inlineScript: Get-AzVM -ResourceGroupName "githubtest"
          azPSVersion: 3.1.0
            az storage -h
